name: boxbot-adzrunner
version: 1.1.7
summary:  AdzRunner Corp.
description: |
  AdzRunner Corp.

confinement: devmode
architectures:
- arm64

apps:
  boxbot-adzrunner:
    command: usr/bin/fbi -T 1 /home/pi/adzrunner/1.jpg
    plugs: [home, network, network-bind, framebuffer, ppp, libvirt]
    daemon: simple
    environment:
      FONTCONFIG_PATH: $SNAP/etc/fonts/config.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf

parts:
  boxbot-adzrunner:
    plugin: dump
    source: https://github.com/ga-con/adz/releases/download/v$SNAPCRAFT_PROJECT_VERSION/adzpi_linux_arm.tar.gz
    build-packages:
     - libjpeg62-dev
     - libpng12-dev
    stage-packages:
     - libc6
     - libexif12
     - libfontconfig1
     - libfreetype6
     - libgif7
     - libjpeg62
     - libpng12-0
     - libtiff5
     - zlib1g
     - ghostscript
     - imagemagick
     - graphicsmagick-imagemagick-compat
     - imagemagick-6.q16
     - fbi
