name: boxbot-adzrunner
version: 1.1.7
summary:  AdzRunner Corp.
description: |
  AdzRunner Corp.

confinement: strict
architectures:
  - build-on: arm64
    run-on: arm64

apps:
  boxbot-adzrunner:
    command: adzpi client --config=/home/pi/adzrunner/config.toml
    plugs: [home, network, network-bind, framebuffer, ppp, libvirt]
    daemon: simple

parts:
  boxbot:
    plugin: dump
    source: https://github.com/ga-con/adz/releases/download/v$SNAPCRAFT_PROJECT_VERSION/adzpi_linux_arm.tar.gz
    stage-packages:
      - libc6
      - libexif12
      - libfontconfig1
      - libfreetype6
      - libgif7
      - libjpeg62-turbo
      - libpng12-0
      - libtiff5
      - zlib1g
      - ghostscript
      - imagemagick
      - imagemagick-6.q16
      - imagemagick-common
      - graphicsmagick-imagemagick-compat
      - fbi
